[build]
  functions = "netlify/functions"

[functions]
  directory = "functions"
  [functions.environment]
    GOOGLE_APPLICATION_CREDENTIALS = "$GOOGLE_APPLICATION_CREDENTIALS"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
