[functions]
  directory = "netlify/functions"

[functions.environment]
  GOOGLE_APPLICATION_CREDENTIALS = "$GOOGLE_APPLICATION_CREDENTIALS"

# rule to handle 404s
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404